// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upwrhzhqpjnarflfctwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwd3JoemhxcGpuYXJmbGZjdHdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTE5NDgsImV4cCI6MjA2NDE2Nzk0OH0.W35SgLIXn5SSyaj3WGD5o3UBDKiLdhPzOrcT6otJFqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);